version: '2'

volumes:
  nextcloud-root:
  nextcloud-config:
  nextcloud-data:
  mariadb:

services:
  mariadb:
    #change this if needed
    image: mariadb-rta:latest
    restart: always
    volumes:
      - mariadb:/var/lib/mysql

  nextcloud:
    #change this if needed
    image: nextcloud-rta:latest
    restart: always
    ports:
      - 8080:80
    links:
      - mariadb
    volumes:
      - nextcloud-root:/var/www/html
      - nextcloud-config:/var/www/html/config
      - nextcloud-data:/var/www/html/data