package_update: true
package_upgrade: true

#clone script and execute
runcmd:
 - sudo su - ubuntu -c "git clone https://github.com/Rodi420/M346_cloud-init"
 - sudo su - ubuntu -c "cd M346_cloud-init && chmod 755 cloud-init-ref04.sh && sudo ./cloud-init-ref04.sh"

